name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          echo "=== Environment Information ==="
          node --version
          npm --version
          
          echo "=== Cleaning npm cache and node_modules ==="
          rm -rf node_modules package-lock.json
          npm cache clean --force
          
          echo "=== Installing dependencies with legacy peer deps ==="
          npm install --legacy-peer-deps --verbose
          
          echo "=== Checking for dependency conflicts ==="
          npm ls --depth=0
          
          echo "=== Checking for specific problematic packages ==="
          npm ls @chakra-ui/react @emotion/react @emotion/styled
          npm ls next react react-dom
          
          echo "=== Final dependency check ==="
          npm list

      - name: Debug Info
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la

      - name: Build
        run: |
          echo "Starting build process..."
          echo "Current directory contents:"
          ls -la
          echo "Running build command..."
          NODE_ENV=production npm run build
          echo "Build completed. Checking output directory..."
          if [ -d ".next" ]; then
            echo "Build output found in .next directory"
            ls -la .next
          else
            echo "No .next directory found"
          fi
          echo "Creating out directory..."
          npm run export
          echo "Export completed. Checking out directory..."
          if [ -d "out" ]; then
            echo "Export output found in out directory"
            ls -la out
          else
            echo "No out directory found"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true 