name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.2'

      - name: Install dependencies
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          NPM_CONFIG_LEGACY_PEER_DEPS: "true"
          NPM_CONFIG_FUND: "false"
          NPM_CONFIG_AUDIT: "false"
        run: |
          echo "=== Environment Information ==="
          node --version
          npm --version
          
          echo "=== Cleaning npm cache and node_modules ==="
          rm -rf node_modules package-lock.json
          npm cache clean --force
          
          echo "=== Installing dependencies ==="
          npm install --no-audit --no-fund --legacy-peer-deps
          
          echo "=== Checking installed packages ==="
          npm list --depth=0

      - name: Build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          NEXT_TELEMETRY_DISABLED: "1"
        run: |
          echo "Starting build process..."
          echo "Current directory contents:"
          ls -la
          echo "Running build command..."
          NODE_ENV=production npm run build
          echo "Build completed. Checking output directory..."
          if [ -d ".next" ]; then
            echo "Build output found in .next directory"
            ls -la .next
          else
            echo "No .next directory found"
          fi
          echo "Creating out directory..."
          npm run export
          echo "Export completed. Checking out directory..."
          if [ -d "out" ]; then
            echo "Export output found in out directory"
            ls -la out
          else
            echo "No out directory found"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true 