name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.2'

      - name: Clean install
        run: |
          echo "=== Cleaning environment ==="
          rm -rf node_modules .next out package-lock.json
          npm cache clean --force
          
          echo "=== Installing dependencies ==="
          npm install --legacy-peer-deps --no-audit --no-fund
          
          echo "=== Checking installed packages ==="
          npm list --depth=0

      - name: Build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          NEXT_TELEMETRY_DISABLED: "1"
          CI: "false"
        run: |
          echo "=== Starting Build Process ==="
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          
          echo "=== Running Build Command ==="
          NODE_ENV=production npm run build
          
          echo "=== Build Completed ==="
          if [ -d ".next" ]; then
            echo "Build output found in .next directory"
            ls -la .next
          else
            echo "No .next directory found"
            exit 1
          fi
          
          echo "=== Creating Static Export ==="
          npm run export
          
          echo "=== Export Completed ==="
          if [ -d "out" ]; then
            echo "Export output found in out directory"
            ls -la out
          else
            echo "No out directory found"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true 