name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Debug Info
      run: |
        node --version
        npm --version
        pwd
        ls -la
    
    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps --no-audit
        npm list
    
    - name: Check TypeScript
      run: |
        npm run type-check || true
    
    - name: Lint
      run: |
        npm run lint || true
    
    - name: Build
      run: |
        echo "Starting build process..."
        npm run build:prod || {
          echo "Build failed. Checking for error logs..."
          if [ -d ".next" ]; then
            echo "Contents of .next directory:"
            ls -la .next/
          fi
          exit 1
        }
        echo "Build completed. Checking output directory..."
        if [ ! -d "out" ]; then
          echo "Error: 'out' directory not created"
          echo "Current directory contents:"
          ls -la
          exit 1
        fi
      env:
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        NEXT_PUBLIC_FIREBASE_CONFIG: ${{ secrets.NEXT_PUBLIC_FIREBASE_CONFIG }}
        CI: false
        DEBUG: "*"
    
    - name: Check build output
      run: |
        echo "Checking build output directory..."
        if [ -d "out" ]; then
          echo "Contents of out directory:"
          ls -la out/
        else
          echo "Error: out directory does not exist"
          echo "Current directory contents:"
          ls -la
          exit 1
        fi
    
    - name: Deploy to cPanel
      if: success() || failure()
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./out/
        server-dir: public_html/
        dangerous-clean-slate: true 