name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.2'

      - name: Clean install
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: "true"
          NPM_CONFIG_FUND: "false"
          NPM_CONFIG_AUDIT: "false"
        run: |
          echo "=== Cleaning environment ==="
          rm -rf node_modules .next out package-lock.json
          npm cache clean --force
          
          echo "=== Installing dependencies in stages ==="
          
          echo "Stage 1: Installing core dependencies"
          npm install --no-audit --no-fund --legacy-peer-deps
          
          echo "Stage 2: Installing webpack dependencies"
          npm install --save-dev --no-audit --no-fund --legacy-peer-deps @svgr/webpack file-loader
          
          echo "Stage 3: Installing remaining dependencies"
          npm install --no-audit --no-fund --legacy-peer-deps
          
          echo "=== Checking installed packages ==="
          npm list --depth=0
          
          echo "=== Checking for dependency conflicts ==="
          npm ls --depth=0 || true

      - name: Build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          NEXT_TELEMETRY_DISABLED: "1"
          CI: "false"
          DEBUG: "webpack:*"
        run: |
          echo "=== Starting Build Process ==="
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          
          echo "=== Running Build Command ==="
          NODE_ENV=production npm run build || {
            echo "Build failed. Checking webpack debug logs..."
            if [ -f ".next/build-error.log" ]; then
              echo "Build error log:"
              cat .next/build-error.log
            fi
            if [ -f ".next/webpack-error.log" ]; then
              echo "Webpack error log:"
              cat .next/webpack-error.log
            fi
            exit 1
          }
          
          echo "=== Build Completed ==="
          if [ -d ".next" ]; then
            echo "Build output found in .next directory"
            ls -la .next
          else
            echo "No .next directory found"
            exit 1
          fi
          
          echo "=== Creating Static Export ==="
          npm run export || {
            echo "Export failed. Checking error logs..."
            if [ -f ".next/export-error.log" ]; then
              echo "Export error log:"
              cat .next/export-error.log
            fi
            exit 1
          }
          
          echo "=== Export Completed ==="
          if [ -d "out" ]; then
            echo "Export output found in out directory"
            ls -la out
          else
            echo "No out directory found"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true 